language: JavaScript, CSS, HTML, react
os: osx

git:
  depth: 3

branches: 
  except:
  -legacy
  -experimental

branches:
  only:
  -main
  -master
  -stable

before_install:
  -react

inatall:
  -npm install @heroicons/react

script:
  -npm install @heroicons/react
  -npm install react-router-dom
  -npm create vite@latest
  -npm install -D tailwindcss postcss autoprefixer
  -npx tailwindcss init -p

before_script:
-

after_script:
  -yarn clean

cache:
  directories:
    -node_modules

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy de proyecto"
  on:
    branch: maIN